#!/usr/bin/env bash
# regen-sentinel-rule-list.sh -- generate the "what Sentinel actually blocks"
# section of docs/teaching/intro-1pager.md from the actual Sentinel repo.
#
# Why this exists: the prior version of intro-1pager.md hand-wrote a list of
# 20 rule IDs from memory, several of which were fabricated. Generating from
# the source of truth makes that class of error impossible. (P0-W1 from the
# 2026-04-28 sixth-pass review.)
#
# Source of truth (in priority order):
#   1. $SENTINEL_REPO env var
#   2. C:/Sentinel (Mahmood's local layout)
#   3. ~/code/Sentinel (student-default layout)
#
# Usage:
#   ./scripts/regen-sentinel-rule-list.sh                # write to intro-1pager.md
#   ./scripts/regen-sentinel-rule-list.sh --to-stdout    # print, don't write
#   ./scripts/regen-sentinel-rule-list.sh --check        # exit 1 if drift
#
# Exit codes:
#   0 - generation succeeded (or --check found no drift)
#   1 - check mode found drift, OR generation failed
#   2 - source Sentinel repo not found

set -u

MODE="write"
case "${1:-}" in
    --to-stdout) MODE="stdout" ;;
    --check)     MODE="check" ;;
    -h|--help)   sed -n '2,18p' "$0"; exit 0 ;;
    "")          ;;
    *)           echo "unknown arg: $1" >&2; exit 2 ;;
esac

# Locate Sentinel.
sentinel="${SENTINEL_REPO:-}"
if [[ -z "$sentinel" ]]; then
    for cand in "C:/Sentinel" "${HOME}/code/Sentinel"; do
        if [[ -d "$cand/sentinel/rules" ]]; then sentinel="$cand"; break; fi
    done
fi
if [[ -z "$sentinel" || ! -d "$sentinel/sentinel/rules" ]]; then
    echo "ERROR: Sentinel repo not found. Set \$SENTINEL_REPO or clone to ~/code/Sentinel." >&2
    exit 2
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$repo_root/docs/teaching/intro-1pager.md"

# Build the rule list as Markdown. Each rule is a one-liner with rule_id +
# the source filename so a reader can grep further.
gen_section() {
    printf '## What Sentinel actually blocks (auto-generated)\n\n'
    printf 'Generated by `scripts/regen-sentinel-rule-list.sh` from `$SENTINEL_REPO`. Do not hand-edit; rerun the script when Sentinel ships new rules.\n\n'

    # YAML rules: filename pattern is <severity>-<slug>.yaml
    printf '### YAML rules (declarative pattern matchers)\n\n'
    for f in "$sentinel"/sentinel/rules/yaml/*.yaml; do
        [[ -f "$f" ]] || continue
        local name; name="$(basename "$f" .yaml)"
        printf -- '- `%s`\n' "$name"
    done
    printf '\n'

    # Plugin rules: filename pattern is <slug>.py
    printf '### Plugin rules (Python checks with custom logic)\n\n'
    for f in "$sentinel"/sentinel/rules/plugins/*.py; do
        [[ -f "$f" ]] || continue
        local name; name="$(basename "$f" .py)"
        case "$name" in __init__|test_*) continue ;; esac
        printf -- '- `%s`\n' "$name"
    done
    printf '\n'

    # Closing note. The authoritative count comes from the rule registry
    # (`sentinel list-rules`): a single source file can register more than one
    # rule, so summing file names under-counts. Fall back to the file sum if
    # the Sentinel package can't be imported in this environment.
    local yaml_count plugin_count registry_count total
    yaml_count="$(find "$sentinel/sentinel/rules/yaml" -maxdepth 1 -name '*.yaml' 2>/dev/null | wc -l | tr -d ' ')"
    plugin_count="$(find "$sentinel/sentinel/rules/plugins" -maxdepth 1 -name '*.py' -not -name '__init__.py' -not -name 'test_*' 2>/dev/null | wc -l | tr -d ' ')"
    registry_count="$( (cd "$sentinel" && python -m sentinel list-rules 2>/dev/null) | grep -cE '\[(BLOCK|WARN|INFO)\]' )"
    if [[ "${registry_count:-0}" -gt 0 ]]; then total="$registry_count"; else total="$((yaml_count + plugin_count))"; fi
    printf '_Total: %s rules as registered by `sentinel list-rules` (source files: %s YAML pattern matchers + %s plugin checks). Each rule has a one-line *why* comment in its source file linking it to the past incident it prevents. Students who think a rule is wrong should fork Sentinel and edit — incident-backed rules are not gospel for every project._\n' "$total" "$yaml_count" "$plugin_count"
}

if [[ "$MODE" == "stdout" ]]; then
    gen_section
    exit 0
fi

# write / check modes need to splice the generated section between markers.
START_MARKER='<!-- BEGIN auto-generated Sentinel rule list -->'
END_MARKER='<!-- END auto-generated Sentinel rule list -->'

if [[ ! -f "$target" ]]; then
    echo "ERROR: target file not found: $target" >&2
    exit 1
fi

if ! grep -q "$START_MARKER" "$target"; then
    echo "ERROR: target $target lacks the BEGIN marker. Insert these lines where you want the rules table:" >&2
    echo "  $START_MARKER" >&2
    echo "  $END_MARKER" >&2
    exit 1
fi

new_section="$(gen_section)"
tmp="$(mktemp)"
awk -v start="$START_MARKER" -v end="$END_MARKER" -v new="$new_section" '
    BEGIN { in_block=0 }
    $0 == start { print; print new; in_block=1; next }
    $0 == end { in_block=0; print; next }
    !in_block { print }
' "$target" > "$tmp"

if [[ "$MODE" == "check" ]]; then
    if ! diff -q "$target" "$tmp" >/dev/null 2>&1; then
        echo "FAIL: $target is out of sync with the Sentinel rule source." >&2
        echo "Fix: bash scripts/regen-sentinel-rule-list.sh" >&2
        rm -f "$tmp"
        exit 1
    fi
    rm -f "$tmp"
    echo "OK: Sentinel rule list in $target matches source."
    exit 0
fi

mv "$tmp" "$target"
echo "Updated $target with $(grep -c '^- \`' "$target") rule entries."
